import { useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";

import { EmptyState } from "@/components/common/EmptyState";
import { ErrorState } from "@/components/common/ErrorState";
import { LoadingState } from "@/components/common/LoadingState";
import { MentorReport } from "@/components/mentor/MentorReport";
import { PageShell } from "@/components/layout/PageShell";
import { api } from "@/lib/api";
import { useMentorStore } from "@/store/mentorStore";

export const ReportPage = () => {
  const { sessionId } = useParams();
  const cached = useMentorStore((state) => state.activeReport);
  const query = useQuery({
    queryKey: ["mentor-report", sessionId],
    queryFn: () => api.getMentorReport(sessionId || ""),
    enabled: Boolean(sessionId && sessionId !== "latest" && cached?.session_id !== sessionId),
  });
  const report = sessionId === "latest" ? cached : cached?.session_id === sessionId ? cached : query.data;

  return (
    <PageShell title="Mentor Report" description="Premium career counseling report generated by the SmartEdu AI mentor engine.">
      {query.isLoading ? <LoadingState /> : query.isError ? <ErrorState message={(query.error as Error).message} /> : report ? <MentorReport payload={report} /> : <EmptyState title="No report selected" message="Generate a mentor report first, then open it here." />}
    </PageShell>
  );
};
