from __future__ import annotations


HIGH_RISK_SAMPLE = {
    "student_id": "DASH_HIGH_001",
    "name": "High Risk Demo Student",
    "department": "Computer Science",
    "year": 3,
    "semester": 5,
    "gender": "Female",
    "attendance_percentage": 58,
    "internal_marks_average": 52,
    "assignment_completion_rate": 50,
    "quiz_average": 48,
    "previous_semester_gpa": 5.9,
    "current_gpa": 5.6,
    "study_hours_per_week": 5,
    "backlogs": 2,
    "late_submissions": 6,
    "participation_score": 42,
    "subject_math_score": 50,
    "subject_programming_score": 47,
    "subject_electronics_score": 55,
    "subject_communication_score": 60,
    "subject_lab_score": 54,
    "library_usage_hours": 1.5,
    "lms_login_frequency": 4,
    "parent_meeting_count": 1,
    "mentor_meeting_count": 1,
    "extracurricular_hours": 1,
    "stress_level": 8,
    "sleep_hours": 5.0,
    "internet_access": "Yes",
}

MEDIUM_RISK_SAMPLE = {
    "student_id": "DASH_MED_001",
    "name": "Medium Risk Demo Student",
    "department": "Information Technology",
    "year": 2,
    "semester": 4,
    "gender": "Male",
    "attendance_percentage": 76,
    "internal_marks_average": 68,
    "assignment_completion_rate": 74,
    "quiz_average": 66,
    "previous_semester_gpa": 7.1,
    "current_gpa": 6.9,
    "study_hours_per_week": 10,
    "backlogs": 0,
    "late_submissions": 2,
    "participation_score": 64,
    "subject_math_score": 62,
    "subject_programming_score": 59,
    "subject_electronics_score": 68,
    "subject_communication_score": 72,
    "subject_lab_score": 70,
    "library_usage_hours": 4,
    "lms_login_frequency": 10,
    "parent_meeting_count": 1,
    "mentor_meeting_count": 2,
    "extracurricular_hours": 3,
    "stress_level": 6,
    "sleep_hours": 6.4,
    "internet_access": "Yes",
}

LOW_RISK_SAMPLE = {
    "student_id": "DASH_LOW_001",
    "name": "Low Risk Demo Student",
    "department": "Data Science",
    "year": 4,
    "semester": 7,
    "gender": "Female",
    "attendance_percentage": 91,
    "internal_marks_average": 86,
    "assignment_completion_rate": 94,
    "quiz_average": 84,
    "previous_semester_gpa": 8.7,
    "current_gpa": 8.8,
    "study_hours_per_week": 17,
    "backlogs": 0,
    "late_submissions": 0,
    "participation_score": 85,
    "subject_math_score": 82,
    "subject_programming_score": 88,
    "subject_electronics_score": 80,
    "subject_communication_score": 86,
    "subject_lab_score": 90,
    "library_usage_hours": 7,
    "lms_login_frequency": 18,
    "parent_meeting_count": 0,
    "mentor_meeting_count": 1,
    "extracurricular_hours": 5,
    "stress_level": 4,
    "sleep_hours": 7.4,
    "internet_access": "Yes",
}

SAMPLES = {
    "High Risk": HIGH_RISK_SAMPLE,
    "Medium Risk": MEDIUM_RISK_SAMPLE,
    "Low Risk": LOW_RISK_SAMPLE,
}
