import type { PredictionRequest } from "./types";

const base: PredictionRequest = {
  student_id: "FRONTEND_DEMO_001",
  name: "Aarav Demo",
  department: "Computer Science",
  year: 3,
  semester: 5,
  gender: "Male",
  attendance_percentage: 78,
  internal_marks_average: 72,
  assignment_completion_rate: 76,
  quiz_average: 70,
  previous_semester_gpa: 7.2,
  current_gpa: 7.0,
  study_hours_per_week: 11,
  backlogs: 0,
  late_submissions: 2,
  participation_score: 68,
  subject_math_score: 71,
  subject_programming_score: 75,
  subject_electronics_score: 66,
  subject_communication_score: 73,
  subject_lab_score: 78,
  library_usage_hours: 3,
  lms_login_frequency: 7,
  parent_meeting_count: 1,
  mentor_meeting_count: 2,
  extracurricular_hours: 2,
  stress_level: 5,
  sleep_hours: 6.8,
  internet_access: "Yes",
};

export const sampleProfiles: Record<"low" | "medium" | "high", PredictionRequest> = {
  low: {
    ...base,
    student_id: "FRONTEND_LOW_001",
    name: "Low Risk Sample",
    attendance_percentage: 91,
    current_gpa: 8.6,
    assignment_completion_rate: 94,
    backlogs: 0,
    stress_level: 3,
    sleep_hours: 7.4,
  },
  medium: {
    ...base,
    student_id: "FRONTEND_MED_001",
    name: "Medium Risk Sample",
    attendance_percentage: 72,
    current_gpa: 6.7,
    assignment_completion_rate: 70,
    late_submissions: 4,
    stress_level: 6,
    sleep_hours: 6,
  },
  high: {
    ...base,
    student_id: "FRONTEND_HIGH_001",
    name: "High Risk Sample",
    attendance_percentage: 58,
    internal_marks_average: 52,
    assignment_completion_rate: 49,
    quiz_average: 47,
    previous_semester_gpa: 5.7,
    current_gpa: 5.4,
    study_hours_per_week: 5,
    backlogs: 2,
    late_submissions: 7,
    participation_score: 42,
    stress_level: 8,
    sleep_hours: 5,
  },
};
